### ISSUE TITLE
Todo for v1.0.0

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#11]
### Todo

- [ ] constant
- [ ] Add a preprocesor
- [ ] handle if function returns void, it can't be used as variable
- [ ] test for all operators
- [ ] default return type
- [ ] Add readonly variables for classes
- [ ] check if class has been initialized
- [ ] call public function or private `e.g. (pub)function()`

- [ ] Add all operators missing
- [ ] Attributes
- [ ] Add a generic system
    - [ ] Functions
    - [ ] Classes
    - [ ] Default types
    - [ ] Infer types without e plicitly typing it
- [ ] Modules
    - [ ] if library ends with .so, dlopen
    - [ ] check entry with a *.json
    - [ ] add a System class for I/O
    - [ ] add system/local modules support
    - [ ] custom variable/selected imports
- [ ] Classes
    - [ ] Class/static keyword
    - [ ] Parse class
    - [ ] Parse class
        - [ ] Function
            - [ ] Support for static
            - [ ] Public methods diferentiate from private methods (can have the same name)
        - [ ] Variables
            - [ ] Support for static
    - [ ] Generate
        - [ ] Struct type
        - [ ] Functions
        - [ ] Variables
        - [ ] Self variable
    - [ ] Call static methods
    - [ ] Inheritance
        - [ ] generate struct with parent fields
        - [ ] Generate parent's functions/variables if they don't e ist
        - [ ] virtual tables/functions
    - [ ] Add `new` keyword support
    - [ ] Add all default override methods

- [ ] Variables
- [ ] Function mangling
- [ ] rework for operators
- [ ] global variables
- [ ] Function creation
    - [ ] Function arguments
- [ ] change location for OPTypes struct inside BinOP node
- [ ] Comments
    - [ ] Normal
    - [ ] Multilines
- [ ] Function return types
- [ ] return statement
    - [ ] parse return statemnt
    - [ ] generate return stmt
    - [ ] check if type of return is equal to function's return type
- [ ] Generate class function to scope before generating blocks
- [ ] change all compiler error to call macro COMPILER_ERROR
- [ ] Perform function calls
    - [ ] pass arguments
    - [ ] pass self argument if it is a class
    - [ ] check if function class is initiated
        - [ ] check if function is static
- [ ] New keyword
- [ ] API
    - [ ] Add a new class
        - [ ] Add a function to class
    - [ ] Add a function
    - [ ] Add class/function to global
- [ ] add optimizations
- [ ] Let user choose in 32/64 bits numbers
- [ ] `alloca` should not really be in the enviroment
- [ ] Unit testing
    - [ ] Add `test` keyword
    - [ ] Parse test statement
    - [ ] check for -t argument
    - [ ] add TestingConte t class
    - [ ] Generate test statement
    - [ ] E ecute tests
    - [ ] return result variable as int
    - [ ] Add things like `assert`
- [ ] Add a Void type
- [ ] Int class
    - [ ] Different types of integers
- [ ] String class
- [ ] Some "built in type" constructors are not found (sometimes)
- [ ] change commands to separated folder/file
    - [ ] compile
    - [ ] build
    - [ ] unit testing
    
### Known Bugs
 
 none?

### None important
- [ ] Add a Any type

**Comment by emm312** [comment]
- [ ] unban emm312 from the discord server

**Comment by mauro-balades** [comment]
rewrite 👍🏽
